spring.application.name=dietary-analysis

# Database configuration (overridable via Environment Variables in Render)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/dietary_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:anupama}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.open-in-view=false

# Port configuration for Render (Render provides the PORT env variable automatically)
server.port=${PORT:8082}